apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vpc-india-testing/workspace.yaml
- vpc-india-testing/configmap.yaml
- ec2-instance/workspace.yaml
- ec2-instance/configmap.yaml
