apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vpc-stage/workspace.yaml
- vpc-stage/configmap.yaml
- vpc-perf/workspace.yaml
- vpc-perf/configmap.yaml
- vpc-preprod-1/workspace.yaml
- vpc-preprod-1/configmap.yaml
