apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- topcupcake/workspace.yaml
- topcupcake/configmap.yaml
- topgun-backstage-dev/workspace.yaml
- topgun-backstage-dev/configmap.yaml
- ec2-coffe-bakstage/workspace.yaml
- ec2-coffe-bakstage/configmap.yaml
