# workspace.yml
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: greetings
spec:
  organization: shridharMe
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git::https://github.com/shridharMe/proton-terraform-demo.git//vpc-dev/?ref=main"
  outputs:
    - key: vpc_id
      moduleOutputName: vpc_id
    - key: private_subnets
      moduleOutputName: private_subnets
    - key: public_subnets
      moduleOutputName: public_subnets
    - key: vpc_cidr_block
      moduleOutputName: vpc_cidr_block
  variables:
    - key: AWS_DEFAULT_REGION
      valueFrom:
        configMapKeyRef:
          name: aws-configuration
          key: region
      sensitive: false
      environmentVariable: true
    - key: AWS_ACCESS_KEY_ID
      sensitive: true
      environmentVariable: true
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
    - key: AWS_SESSION_TOKEN
      sensitive: true
      environmentVariable: true
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true