apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: vpc-demo-wed-6
  namespace: edu
spec:
  module:
    source: git::https://github.com/shridharMe/proton-terraform-demo//vpc-demo-wed-6/?ref=1.0.75
  organization: shridharMe
  outputs:
  - key: vpc_id
    moduleOutputName: vpc_id
  - key: private_subnets
    moduleOutputName: private_subnets
  - key: public_subnets
    moduleOutputName: public_subnets
  - key: vpc_cidr_block
    moduleOutputName: vpc_cidr_block
  secretsMountPath: /tmp/secrets
  variables:
  - environmentVariable: true
    key: AWS_DEFAULT_REGION
    sensitive: false
    valueFrom:
      configMapKeyRef:
        key: region
        name: aws-configuration-vpc-demo-wed-6
  - environmentVariable: true
    key: CONFIRM_DESTROY
    sensitive: false
    value: '1'
